server:
  port: 8080

spring:
  datasource:
    url: jdbc:h2:mem:garderie_db
    username: sa
    password: 1234
    driver-class-name: org.h2.Driver
  security:
    user:
      name: user
      password: pass
      roles: USER
  h2:
    console:
      enabled: true

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create
    database-platform: org.hibernate.dialect.H2Dialect

application:
  jwt:
    expiresAt: 846000
    headerPrefix: "Bearer "
    secret: "Y2nr@Svs1#Rume@v9^r$$hwTm563QpxLfdDTO$VdLLMnNRJmcQ"
    headerKey: "Authorization"

custom:
  property: "ma prop custom"
  other: "thing"
  number: 3
  list:
    - 1
    - 2
    - 3